services:
  postgresql_17_db:
    container_name: postgresql_17_db
    image: postgres:17
    environment:
      POSTGRES_DB: task_management_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d task_management_system_db" ]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - task_management_system_app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  task_management_system:
    container_name: task_management_system
    image: openjdk:21-jdk
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql_17_db:5432/task_management_system_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./target/task-management-system-0.0.1-SNAPSHOT.jar:/app.jar
    command: [ "java", "-jar", "/app.jar" ]
    restart: always
    networks:
      - task_management_system_app
    depends_on:
      - postgresql_17_db
    env_file:
      - .env

networks:
  task_management_system_app:
