server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql_17_db:5432/task_management_system_db
    username: postgres
    password: 123

  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      format_sql: true
      highlight_sql: true
      hibernate:
        use_sql_comments: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  application:
    name: Task management system

logging:
  level:
    org.springframework.security: error

app:
  name: Task management system
  description: An application for managing tasks. You can assign performers and leave comments on tasks.
  version: v.1.0.0
  email: task-management-system@gmail.com

jwt:
  secret_key: "ESFTR0MDXp9ZBcAQ+kAWo+IHDe/Sr4+5ZAKCw/VxE6w="
  access_token_expiration: 900000 # 15 минут в миллисекундах
  refresh_token_expiration: 604800000 # 7 дней в миллисекундах