server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql_17_db:5432/task_management_system_db
    username: postgres
    password: 123

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      format_sql: true
      highlight_sql: true
      hibernate:
        use_sql_comments: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  application:
    name: Task management system

app:
  name: Task management system
  description: An application for managing tasks. You can assign performers and leave comments on tasks.
  version: v.1.0.0
  email: task-management-system@gmail.com